//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocal.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocal.Business.Properties.Resources.Language", typeof(Resources_Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le lien pour modifier mot de passe &lt;a target=&quot;_blank&quot; href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string AskPassword {
            get {
                return ResourceManager.GetString("AskPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string AskPasswordSubject {
            get {
                return ResourceManager.GetString("AskPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce token n&apos;est pas valide.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet email existe déja.
        /// </summary>
        public static string MailExisting {
            get {
                return ResourceManager.GetString("MailExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet email n&apos;existe pas.
        /// </summary>
        public static string MailNotExisting {
            get {
                return ResourceManager.GetString("MailNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe n&apos;est pas au bon format.
        /// </summary>
        public static string PasswordRegex {
            get {
                return ResourceManager.GetString("PasswordRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe requis.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe bien modifié.
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur technique, réessayez plus tard.
        /// </summary>
        public static string TechnicalError {
            get {
                return ResourceManager.GetString("TechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai d&apos;attente dépassé.
        /// </summary>
        public static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Unauthorize {
            get {
                return ResourceManager.GetString("Unauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;identification 2.
        /// </summary>
        public static string UserinfoError {
            get {
                return ResourceManager.GetString("UserinfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce nom d&apos;utilisateur existe déjà.
        /// </summary>
        public static string UsernameExisting {
            get {
                return ResourceManager.GetString("UsernameExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce nom d&apos;utilisateur n&apos;existe pas.
        /// </summary>
        public static string UsernameNotExisting {
            get {
                return ResourceManager.GetString("UsernameNotExisting", resourceCulture);
            }
        }
    }
}
